---
- name: Manage AWS Security Groups
  hosts: localhost
  gather_facts: False
  vars_files:
    - secrets.yml
  vars:
    region: "us-east-1"
    security_group_name: "tamil-security-group"
    vpc_id: "vpc-03ea4b3e44d7bf10f"
  tasks:
    - name: Create Security Group
      ec2_group:
        name: "{{ security_group_name }}"
        description: "Creating group name for ec2 instances"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2_create_sgrp
    - debug:
        msg: "{{ ec2_create_sgrp }}"
    - debug:
        msg: "{{ security_group_name }} created successfully"  
      when: ec2_create_sgrp.changed
